In [28]:
!pip install nltk
import nltk

nltk.download('punkt_tab')

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: nltk in c:\users\royal wala\appdata\roaming\python\python314\site-packages (3.10.2)
Requirement already satisfied: defusedxml in c:\users\royal wala\appdata\roaming\python\python314\site-packages (from nltk) (0.7.1)
Requirement already satisfied: click in c:\users\royal wala\appdata\roaming\python\python314\site-packages (from nltk) (8.3.3)
Requirement already satisfied: joblib in c:\users\royal wala\appdata\roaming\python\python314\site-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in c:\users\royal wala\appdata\roaming\python\python314\site-packages (from nltk) (2026.7.19)
Requirement already satisfied: tqdm in c:\users\royal wala\appdata\roaming\python\python314\site-packages (from nltk) (4.70.0)
Requirement already satisfied: colorama in c:\users\royal wala\appdata\roaming\python\python314\site-packages (from click->nltk) (0.4.6)

[notice] A new release of pip is available: 25.3 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip
[nltk_data] Downloading package punkt_tab to C:\Users\ROYAL
[nltk_data]     WALA\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt_tab.zip.

True

In [29]:
import nltk
from nltk.corpus import wordnet, stopwords
from nltk.stem import WordNetLemmatizer
from nltk import word_tokenize, pos_tag

In [30]:
# Download Required Packages...
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('averaged_perceptron_tagger')
nltk.download('averaged_perceptron_tagger_eng')

[nltk_data] Downloading package stopwords to C:\Users\ROYAL
[nltk_data]     WALA\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to C:\Users\ROYAL
[nltk_data]     WALA\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\ROYAL WALA\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     C:\Users\ROYAL WALA\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!

True

In [31]:
st = ["better"]
pos_tag(st) # if pos_tag starts with R or J it will be an Adjective

[('better', 'RBR')]

In [32]:
# POS Mapping Function
def get_wordnet_pos(tag):
    if tag.startswith("j"):
        return 'a'
    elif tag.startswith("R"):
        return 'a'

In [33]:
lemmatizer = WordNetLemmatizer()

In [34]:
lemmatizer.lemmatize(st[0], pos=get_wordnet_pos(pos_tag(st)[0][1]))

'good'

In [36]:
pos_tag(st)

[('better', 'RBR')]

In [37]:
# POS Mapping Function
def get_wordnet_pos(tag):
    if tag.startswith("j"):
        return 'a'
    elif tag.startswith("R"):
        return 'a'
    elif tag.startswith("N"):
        return 'n'
    elif tag.startswith("A"):
        return 'a'
    elif tag.startswith("V"):
        return 'v'
    else:
        return 'n'

In [38]:
text = "My better friend is playing football in the ground with his friends"

In [39]:
# Tokenizer
token = word_tokenize(text.lower())
token

['my',
 'better',
 'friend',
 'is',
 'playing',
 'football',
 'in',
 'the',
 'ground',
 'with',
 'his',
 'friends']

In [41]:
stop_words = set(stopwords.words('english'))
len(stop_words)

198

In [43]:
tokens = [t for t in token if t not in stop_words]
tokens

['better', 'friend', 'playing', 'football', 'ground', 'friends']

In [44]:
tags = pos_tag(tokens)

In [45]:
tags

[('better', 'RBR'),
 ('friend', 'NN'),
 ('playing', 'VBG'),
 ('football', 'NN'),
 ('ground', 'NN'),
 ('friends', 'NNS')]

In [46]:
lemmatizer = WordNetLemmatizer()

In [47]:
final_token = []

In [51]:
for word, tag in tags:
    wordnet_pos = get_wordnet_pos(tag)
    w = lemmatizer.lemmatize(word)
    final_token.append(w)
final_token

['better', 'friend', 'playing', 'football', 'ground', 'friend']

In [52]:
# Sentiment Analysis
import pandas as pd

In [53]:
dataset = {
    'text':[
        'I love this product',
        'I love NLP',
        'I hate Maths',
        'I hate this service',
        'I love this book',
        'I hate you'
    ],
    'labels':[1,1,0,0,1,0] # 1 = positive, 0 = negative
}

In [54]:
df = pd.DataFrame(dataset)

In [55]:
df

                  text  labels
0  I love this product       1
1           I love NLP       1
2         I hate Maths       0
3  I hate this service       0
4     I love this book       1
5           I hate you       0

In [58]:
# Preprocessing of dataset
def preprocess(text):
    text = word_tokenize(text.lower())
    text = [w for w in text if  w not in stop_words]
    new_text = []
    for w in text:
        new_text.append(lemmatizer.lemmatize(w, pos= get_wordnet_pos(pos_tag([w])[0][1] )) )
    return " ".join(new_text)

In [59]:
data = df['text'].map(preprocess)
data

0    love product
1        love nlp
2       hate math
3    hate service
4       love book
5            hate
Name: text, dtype: str

In [61]:
df['text'] = df['text'].map(preprocess)
df

           text  labels
0  love product       1
1      love nlp       1
2     hate math       0
3  hate service       0
4     love book       1
5          hate       0

In [62]:
# converting text into numerical values, it will called VECTOR DATABASE
# To create vector DB (TF-IDF)

In [64]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [65]:
tfidf = TfidfVectorizer()

In [80]:
# split data into x and y
X= tfidf.fit_transform(df['text'])
y = df['labels']

In [81]:
X

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 11 stored elements and shape (6, 7)>

In [83]:
X.toarray()

array([[0.        , 0.        , 0.56921261, 0.        , 0.        ,
        0.82219037, 0.        ],
       [0.        , 0.        , 0.56921261, 0.        , 0.82219037,
        0.        , 0.        ],
       [0.        , 0.56921261, 0.        , 0.82219037, 0.        ,
        0.        , 0.        ],
       [0.        , 0.56921261, 0.        , 0.        , 0.        ,
        0.        , 0.82219037],
       [0.82219037, 0.        , 0.56921261, 0.        , 0.        ,
        0.        , 0.        ],
       [0.        , 1.        , 0.        , 0.        , 0.        ,
        0.        , 0.        ]])

In [84]:
tfidf_df = pd.DataFrame(x.toarray(), columns = tfidf.get_feature_names_out())

In [85]:
tfidf_df

      book      hate      love     math      nlp  product  service
0  0.00000  0.000000  0.569213  0.00000  0.00000  0.82219  0.00000
1  0.00000  0.000000  0.569213  0.00000  0.82219  0.00000  0.00000
2  0.00000  0.569213  0.000000  0.82219  0.00000  0.00000  0.00000
3  0.00000  0.569213  0.000000  0.00000  0.00000  0.00000  0.82219
4  0.82219  0.000000  0.569213  0.00000  0.00000  0.00000  0.00000
5  0.00000  1.000000  0.000000  0.00000  0.00000  0.00000  0.00000

In [86]:
from sklearn.linear_model import LogisticRegression

In [87]:
model = LogisticRegression()

In [88]:
model.fit(X,y)

LogisticRegression()

In [89]:
model.predict(tfidf_df)

C:\Users\ROYAL WALA\AppData\Roaming\Python\Python314\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(

array([1, 1, 0, 0, 1, 0])