In [13]:
import pandas as pd

In [14]:
neg = pd.read_csv('../dataset/negative.csv')
pos = pd.read_csv('../dataset/positive.csv')

In [15]:
df = pd.concat([neg, pos])

In [16]:
df.shape

(726730, 3)

In [17]:
df.head(2)

                                                text  count  status
0   I am so angry that i made this post available...      1       0
1   Rooms are nice but for elderly a bit difficul...      1       0

In [18]:
df = df.drop(columns=["count"])

In [20]:
df.head(2)

                                                text  status
0   I am so angry that i made this post available...       0
1   Rooms are nice but for elderly a bit difficul...       0

In [21]:
df

                                                     text  status
0        I am so angry that i made this post available...       0
1        Rooms are nice but for elderly a bit difficul...       0
2        My room was dirty and I was afraid to walk ba...       0
3        You When I booked with your company on line y...       0
4        Backyard of the hotel is total mess shouldn t...       0
...                                                   ...     ...
403179   The breakfast was excelent lots of fress frui...       1
403180   helpful staff allowed me to check in early as...       1
403181      Breakfast was ok and we got earlier check in        1
403182   The rooms are enormous and really comfortable...       1
403183                               staff was very kind        1

[726730 rows x 2 columns]